require:
  - rubocop-rake

# TODO: Security/Eval is required for the .homesickrc feature. This should
# eventually be removed if the feature is implemented in a more secure way.
Security/Eval:
  Enabled: false

# TODO: The following settings disable reports about issues that can be fixed
# through refactoring. Remove these as offenses are removed from the code base.

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 13

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 36
