plugins:
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

# Explicit maxes that reflect the current code. Reduce these incrementally
# as methods are refactored further.

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 255

Metrics/CyclomaticComplexity:
  Max: 10

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Max: 213

Metrics/ParameterLists:
  Max: 6

Metrics/PerceivedComplexity:
  Max: 11

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
