# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: homesick 1.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "homesick"
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Joshua Nichols", "Yusuke Murata"]
  s.date = "2014-05-22"
  s.description = "\n    Your home directory is your castle. Don't leave your dotfiles behind.\n    \n\n    Homesick is sorta like rip, but for dotfiles. It uses git to clone a repository containing dotfiles, and saves them in ~/.homesick. It then allows you to symlink all the dotfiles into place with a single command. \n\n  "
  s.email = ["josh@technicalpickles.com", "info@muratayusuke.com"]
  s.executables = ["homesick"]
  s.extra_rdoc_files = [
    "ChangeLog.markdown",
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rubocop.yml",
    ".travis.yml",
    "ChangeLog.markdown",
    "Gemfile",
    "Guardfile",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "bin/homesick",
    "homesick.gemspec",
    "lib/homesick.rb",
    "lib/homesick/actions/file_actions.rb",
    "lib/homesick/actions/git_actions.rb",
    "lib/homesick/cli.rb",
    "lib/homesick/shell.rb",
    "lib/homesick/utils.rb",
    "lib/homesick/version.rb",
    "spec/homesick_cli_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/technicalpickles/homesick"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Your home directory is your castle. Don't leave your dotfiles behind."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thor>, [">= 0.14.0"])
      s.add_development_dependency(%q<rake>, [">= 0.8.7"])
      s.add_development_dependency(%q<rspec>, ["~> 2.10"])
      s.add_development_dependency(%q<guard>, [">= 0"])
      s.add_development_dependency(%q<guard-rspec>, [">= 0"])
      s.add_development_dependency(%q<rb-readline>, ["~> 0.5.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.6.2"])
      s.add_development_dependency(%q<coveralls>, [">= 0"])
      s.add_development_dependency(%q<test_construct>, [">= 0"])
      s.add_development_dependency(%q<capture-output>, ["~> 1.0.0"])
      s.add_development_dependency(%q<rubocop>, [">= 0"])
    else
      s.add_dependency(%q<thor>, [">= 0.14.0"])
      s.add_dependency(%q<rake>, [">= 0.8.7"])
      s.add_dependency(%q<rspec>, ["~> 2.10"])
      s.add_dependency(%q<guard>, [">= 0"])
      s.add_dependency(%q<guard-rspec>, [">= 0"])
      s.add_dependency(%q<rb-readline>, ["~> 0.5.0"])
      s.add_dependency(%q<jeweler>, [">= 1.6.2"])
      s.add_dependency(%q<coveralls>, [">= 0"])
      s.add_dependency(%q<test_construct>, [">= 0"])
      s.add_dependency(%q<capture-output>, ["~> 1.0.0"])
      s.add_dependency(%q<rubocop>, [">= 0"])
    end
  else
    s.add_dependency(%q<thor>, [">= 0.14.0"])
    s.add_dependency(%q<rake>, [">= 0.8.7"])
    s.add_dependency(%q<rspec>, ["~> 2.10"])
    s.add_dependency(%q<guard>, [">= 0"])
    s.add_dependency(%q<guard-rspec>, [">= 0"])
    s.add_dependency(%q<rb-readline>, ["~> 0.5.0"])
    s.add_dependency(%q<jeweler>, [">= 1.6.2"])
    s.add_dependency(%q<coveralls>, [">= 0"])
    s.add_dependency(%q<test_construct>, [">= 0"])
    s.add_dependency(%q<capture-output>, ["~> 1.0.0"])
    s.add_dependency(%q<rubocop>, [">= 0"])
  end
end

