# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |spec|
  spec.name = "homesick"
  spec.version = "0.9.8"

  spec.required_rubygems_version = Gem::Requirement.new(">= 0") if spec.respond_to? :required_rubygems_version=
  spec.authors = ["Joshua Nichols", "Yusuke Murata"]
  spec.date = "2013-12-31"
  spec.description = "\n    A man's home (directory) is his castle, so don't leave home with out it.\n\n    Homesick is sorta like rip, but for dotfiles. It uses git to clone a repository containing dotfiles, and saves them in ~/.homesick. It then allows you to symlink all the dotfiles into place with a single command. \n\n  "
  spec.email = ["josh@technicalpickles.com", "info@muratayusuke.com"]
  spec.executables = ["homesick"]
  spec.extra_rdoc_files = [
    "ChangeLog.markdown",
    "LICENSE",
    "README.markdown"
  ]
  spec.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "ChangeLog.markdown",
    "Gemfile",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "bin/homesick",
    "homesick.gemspec",
    "lib/homesick.rb",
    "lib/homesick/actions.rb",
    "lib/homesick/shell.rb",
    "spec/homesick_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  spec.homepage = "http://github.com/technicalpickles/homesick"
  spec.licenses = ["MIT"]
  spec.require_paths = ["lib"]
  spec.rubygems_version = "1.8.23"
  spec.summary = "A man's home is his castle. Never leave your dotfiles behind."

  spec.add_runtime_dependency "thor", ">= 0.14.0"

  spec.add_development_dependency "bundler", "~> 1.5"
  spec.add_development_dependency "rake"
  spec.add_development_dependency "rspec"
  spec.add_development_dependency "jeweler", ">= 1.6.2"
  spec.add_development_dependency "rcov", ">= 0"
  spec.add_development_dependency "simplecov", ">= 0"
  spec.add_development_dependency "test-construct", ">= 0"
  spec.add_development_dependency "rubocop", ">= 0"
end

